config:
  credentials:
  - id: upv_im_id
    password_var: IM_PASS
    username_var: IM_USER
  - id: incd_openstack_id
    password_var: OPENSTACK_PASS
    username_var: OPENSTACK_USER
  project_repos:
    github.com/EOSC-synergy/saps-deploy:
      branch: master
      repo: https://github.com/EOSC-synergy/saps-deploy
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: release/1.7.11
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  SvcQC.Dep:
    repos:
      this_repo:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-linen-flounder.sh
        container: svcqc.dep_shaky-ecru-bear
timeout: 5400
